### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by jjok** [rusty-dev/mopidy-deezer#14] opened 2017-01-10 22:30 UTC
The extension seems to not be working today. I'm guessing that Deezer have changed their API. It'll need some looking in to.

I'm not getting any errors when I try to list Artists, Albums, Flow or Mixes, just no results.

Listing Moods gives this error:

```
2017-01-10 22:27:02,633 ERROR [678:DeezerBackend-4] mopidy_deezer.deezer: Error during deezer api call, method: deezer.pageMoods, params: {'start': 0, 'nb': 100, 'type': 'playlist', 'genre_id': 0}, error: {u'GATEWAY_ERROR': u'invalid api token'}
2017-01-10 22:27:02,643 ERROR [678:Core-8] mopidy.core.library: DeezerBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/library.py", line 49, in browse
    return browse_func()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 282, in browse_moods
    for playlist in data['ITEMS']['data']:
KeyError: 'ITEMS'
```

**Comment by jjok** [comment] 2017-01-10 22:46
If I go to deezer.com, the API key it gives me contains `~` `-` and `_` characters as well as numbers and both upper and lower case letters. I don't think this is covered by the current regex `([\w\d]+)`.

Maybe something like `([\w~-]+)` would do? (I think `\w` includes letters, numbers and underscore, so I don't think `\d` is required)

**Comment by rusty-dev** [comment] 2017-01-10 23:09
Not sure if the error above is caused by an invalid token, but token parsing was definitely broken. Your proposed regex does seem to cover all the required token cases.

Can you test if it works right now? I don't have a working mopidy environment right now.

**Comment by jjok** [comment] 2017-01-11 08:34
I'l give it a test either tonight or tomorrow.

**Comment by FinrodFelagund** [comment] 2017-01-11 19:54
Tried the fix, and the invalid api token error doesn't show anymore. Browsing Artists, Albums, Flows and Mixes works, as well as Search.

Moods is still broken, but throws a different error now:
```
2017-01-11 19:46:19,464 ERROR [1320:DeezerBackend-3] mopidy_deezer.deezer: Error during deezer api call, method: deezer.pageMoods, params: {'start': 0, 'nb': 100, 'type': 'playlist', 'genre_id': 0}, error: {u'MISSING_PARAMETER_ID': u'Parameter ID is missing'}
2017-01-11 19:46:19,467 ERROR [1320:Core-8] mopidy.core.library: DeezerBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/library.py", line 49, in browse
    return browse_func()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 282, in browse_moods
    for playlist in data['ITEMS']['data']:
KeyError: 'ITEMS'
```

**Comment by rusty-dev** [comment] 2017-01-11 21:19
That's probably because they removed moods altogether. I don't see it in deezer web interface.

**Comment by jjok** [comment] 2017-01-12 08:42
I've #15 to fix/remove Moods.

I haven't tried this fix, but I should be able to do that tonight.

**Comment by jjok** [comment] 2017-01-12 20:22
Yep. It seems to all be working again (except Moods). Thanks.

**Comment by pzalvec** [comment] 2017-01-13 10:44
It seems that at least the `.` is also needed.

**Comment by rusty-dev** [comment] 2017-01-13 10:54
Added `.`

**Comment by jjok** [comment] 2017-01-13 11:04
I assume a `.` is literal when it's inside a character range `[.]`, as opposed to "any character" which it would normally mean in a regex?

**Comment by rusty-dev** [comment] 2017-01-13 11:06
correct

**Comment by jjok** [comment] 2017-01-16 21:04
Huh. It seems to have just broken again. I'll try and find out what my API key is. Maybe we need to add more to the regex.

```
2017-01-16 21:02:22,217 ERROR [959:DeezerBackend-4] mopidy_deezer.deezer: Error during deezer api call, method: deezer.pageProfile, params: {'nb': 1000, 'user_id': 367581215, 'tab': 'artists'}, error: {u'GATEWAY_ERROR': u'invalid api token'}
2017-01-16 21:02:22,220 ERROR [959:Core-8] mopidy.core.library: DeezerBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/library.py", line 49, in browse
    return browse_func()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 216, in browse_artists
    for artist in data['TAB']['artists']['data']:
KeyError: 'TAB'
```

**Comment by jjok** [comment] 2017-01-16 21:12
Hmmm. I restarted the server and it's working again.

Could it be that the API key that I was using expired?

**Comment by rusty-dev** [comment] 2017-01-16 21:37
not unless they've changed the behavior of invalid tokens: https://github.com/rusty-dev/mopidy-deezer/blob/master/mopidy_deezer/deezer.py#L144
My guess is that there's just some other symbol in the token that is not covered by regex.

**Comment by FinrodFelagund** [comment] 2017-01-21 21:39
I had a similar issue as @jjok on my Raspberry Pi 3. After a few reboots it would sometimes start working again, with a new api token I suppose.

After b7a51f39aa01bebdd81fa9599a09b37e866d0119 the regexp was interpreted as an (invalid) character range. Escaping `-` solves this, turning the regexp into `([\w~\-.]+)`. See #16 for a fix.

**Comment by rusty-dev** [comment] 2017-01-21 22:04
@FinrodFelagund merged your PR, the issue should be resolved now. Reopen if necessary.

**Closed by rusty-dev** 2017-01-21 22:04 UTC
